### ISSUE TITLE
The plugin seems to be broken

### ISSUE THREAD

**Issue by shiv19** [TheOriginalJosh/nativescript-parallax#13]
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onItemClick failed

Error: Building UI from XML. @file:///app/views/coming-soon/coming-soon.xml:28:7
 > Module '/data/data/com.somecompany.someapp/files/app/tns_modules/nativescript-parallax' not found for element 'nativescript-parallax:ParallaxView'.
   > First argument should be number, second argument should be string.
File: "file:///data/data/com.somecompany.someapp/files/app/tns_modules/tns-core-modules/ui/builder/builder.js, line: 195, column: 20

StackTrace: 
    Frame: function:'ScopeError', file:'file:///data/data/com.somecompany.someapp/files/app/tns_modules/tns-core-modules/utils/debug.js', line: 17, column: 24
    Frame: function:'SourceError', file:'file:///data/data/com.somecompany.someapp/files/app/tns_modules/tns-core-modules/utils/debug.js', line: 28, column: 23
    Frame: function:'', file:'file:///data/data/com.somecompany.someapp/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 214, column: 17
    Frame: function:'', file:'file:///data/data/com.somecompany.someapp/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 195, column: 33
    Frame: function:'', file:'file:///data/data/com.somecompany.someapp/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 148, column: 13
    Frame: function:'EasySAXParser.parse', file:'file:///data/data/com.somecompany.someapp/files/app/tns_modules/tns-core-modules/js-libs/easysax/easysax.js', line: 751, column: 23
    Frame: function:'XmlParser.parse', file:'file:///data/data/com.somecompany.someapp/files/app/tns_modules/tns-core-modules/xml/xml.js', line: 195, column: 22
    Frame: function:'XmlStringParser.parse', file:'file:///data/data/com.somecompany.someapp/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 201, column: 27
    Frame: function:'parseInternal', file:'file:///data/data/com.somecompany.someapp/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 46, column: 11
    Frame: function:'loadPage', file:'file:///data/data/com.somecompany.someapp/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 130, column: 27
    Frame: function:'pageFromBuilder', file:'file:///data/data/com.somecompany.someapp/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 128, column: 26
    Frame: function:'resolvePageFromEntry', file:'file:///data/data/com.somecompany.someapp/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 112, column: 20
    Frame: function:'FrameBase.navigate', file:'file:///data/data/com.somecompany.someapp/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 180, column: 20
    Frame: function:'', file:'file:///data/data/com.somecompany.someapp/files/app/views/dashboard/explore/explore.js', line: 28, column: 35
    Frame: function:'Observable.notify', file:'file:///data/data/com.somecompany.someapp/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 103, column: 23
    Frame: function:'ItemClickListenerImpl.onItemClick', file:'file:///data/data/com.somecompany.someapp/files/app/tns_modules/tns-core-modules/ui/list-view/list-view.js', line: 29, column: 19

    at com.tns.Runtime.callJSMethodNative(Native Method)
    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1043)
    at com.tns.Runtime.callJSMethodImpl(Runtime.java:925)
    at com.tns.Runtime.callJSMethod(Runtime.java:912)
    at com.tns.Runtime.callJSMethod(Runtime.java:896)
    at com.tns.Runtime.callJSMethod(Runtime.java:888)
    at com.tns.gen.java.lang.Object_frnal_ts_helpers_l58_c38__ItemClickListenerImpl.onItemClick(Object_frnal_ts_helpers_l58_c38__ItemClickListenerImpl.java:15)
    at android.widget.AdapterView.performItemClick(AdapterView.java:339)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1705)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:4171)
    at android.widget.AbsListView$13.run(AbsListView.java:6735)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6682)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by shiv19** [comment]
I think this is because i was on version 1.1.0,
when i did npm upgrade nativescript-parallax, it got upgraded to 1.2.0,

but in the git source it says 1.4.0 in the package json. why isn't the latest version available in npm?

**Comment by shiv19** [comment]
1.2.0, also has the same problem. Looking forward to the release of 1.4.0

**Comment by shiv19** [comment]
UPDATE: Even on 1.4.0, the same problem exists

**Comment by Aris-ngoy** [comment]
i have been experiencing the same problem on nativescript 3.2

**Comment by felipemullen** [comment]
the problem file can be found at `node_modules/nativescript-parallax/nativescript-parallax.js` where `GridUnitType.star` is passed as a second argument but the property is `undefined`

```
var row = new grid_layout_1.ItemSpec(2, grid_layout_1.GridUnitType.star);
var column = new grid_layout_1.ItemSpec(1, grid_layout_1.GridUnitType.star);
```

I've inspected the code and found the property name should be accessed as `STAR` according to what is in the object:
```
GridUnitType: {
   PIXEL: "pixel",
   STAR: "star",
   AUTO: "auto"
}
```

A temporary fix is to change lines 69 and 70 to:
```
var row = new grid_layout_1.ItemSpec(2, grid_layout_1.GridUnitType.STAR);
var column = new grid_layout_1.ItemSpec(1, grid_layout_1.GridUnitType.STAR);
```

Note, that I had to rebuild in order for it to work:

![image](https://user-images.githubusercontent.com/3488482/32149613-723325b6-bcc4-11e7-94d7-2fff7f87365a.png)

**Comment by felipemullen** [comment]
After looking at the code found in `nativescript-parallax.ts` it looks like the change has already been made. It may just be a matter of the author updating the plugin in NPM

**Comment by shiv19** [comment]
@felipemullen if you want tgz of latest plugin, get it from here
https://github.com/NativeScript/NativeScript/issues/4908

**Comment by JoshDSommer** [comment]
Morning guy's, I just published the master branch version. 1.4.0 lets see if that works better.

**Comment by shiv19** [comment]
super 👍 @TheOriginalJosh

**Comment by felipemullen** [comment]
1.4.0 works well for my existing code. This issue can be closed IMO
