### ISSUE TITLE
how can i do this in nativescript angular application?

### ISSUE THREAD

**Issue by MuhammadTahir92** [TheOriginalJosh/nativescript-parallax#14]

**Comment by JoshDSommer** [comment]
Hi @MuhammadTahir92 I wouldn't recommend using this anymore.  here is a better example of creating a parallax scroll https://play.nativescript.org/?template=play-ng&id=DXJkOJ&v=9

**Comment by tigrenok00** [comment]
@TheOriginalJosh 
Hi! The the playground example is great when you are able to use ScrollView and regular layouts inside, however, I would like the scrollable (bottom) part to be a ListView, and putting ListView inside a ScrollView won't work. Is it something that could be achieved using your plugin in angular app? Appreciate your advice!
Thank you!

**Comment by JoshDSommer** [comment]
@tigrenok00 Unfortunately No, I don't think this will work in your situation, unfortunately, the list view to my knowledge doesn't have the necessary API to hook into to get the vertical offset.
