### ISSUE TITLE
parallax not working

### ISSUE THREAD

**Issue by dwi-lanang** [TheOriginalJosh/nativescript-parallax#2]
i create new project and follow instruction TheOriginalJosh/nativescript-parallax but paralax effect not working

**Comment by bradmartin** [comment]
@dwilanang - try the new updates. Also if you're building/cloning the repo make sure you transpile the TS files before running.

**Comment by JoshDSommer** [comment]
Thank you for your feedback. Please pull down the latest version  it's a pretty big update and should fix your issues. I'm pretty sure I had committed a breaking change early.

**Comment by JoshDSommer** [comment]
@dwilanang  I'm going to go ahead and close this out. If you still have problems don't hestiate to open another issue. and Thanks for your feedback.

**Comment by dwi-lanang** [comment]
parallax is working, thank you for your help ;)

**Comment by JoshDSommer** [comment]
@dwilanang awesome! thanks for letting me know. if you have any other problems hit me up.
