### ISSUE TITLE
Enhancement: Prevent scroll event - when Anchored at top

### ISSUE THREAD

**Issue by bradmartin** [TheOriginalJosh/nativescript-parallax#3]
Not sure the best approach, possibly a simple boolean flag to check if the scroll view has reached the end of it's scrolling and then prevent firing the events. On Android 4.4 device the Anchored view is jumping, I believe it's still firing events. I didn't have time to do logs and see if it's executing as I think it is.

![jumping](https://cloud.githubusercontent.com/assets/6006148/14516673/1c62a914-01cb-11e6-92da-67270adebebf.gif)

**Comment by JoshDSommer** [comment]
I've got an update in 1.1.0 that allows disabling the over-scroll/bounce effect that is the cause of this. I'm defaulting it to true to start with but it can be disabled if anyone wants the bounce effect still.
