### ISSUE TITLE
Error: View already has parent when resuming Android

### ISSUE THREAD

**Issue by bradmartin** [TheOriginalJosh/nativescript-parallax#5]
![screenshot_20160413-230639](https://cloud.githubusercontent.com/assets/6006148/14516825/94c967ac-01cc-11e6-9610-ecda209164c6.png)

This occurs when you resume the Android app. So run, put into background and open again and it should crash. Happened a few times on different android devices so should be able to recreate it 😄

**Comment by bradmartin** [comment]
If you need help with this, Nathanael Anderson is probably your best resource to ask on the events and a possible work around.

**Comment by JoshDSommer** [comment]
Great Info man. I've got a fix in place for this and merged.
