### ISSUE TITLE
Can use tns-core-modules@1.6.2 for this plugin?

### ISSUE THREAD

**Issue by katturajam** [TheOriginalJosh/nativescript-parallax#9]
I tried this plugin tns-core-modules@1.6.2, controlToFade is not working. That is scroll with parrallax effect is not working. Our project built with 1.6.2 but i am not able upgrade so that i enquire can we downgarde to use this plugin

**Comment by JoshDSommer** [comment]
I'm going to close this issue, I'm sorry at this time I don't think it's possible to downgrade it to 1.6.2 without more work. there is a public utilities class that is exposed and it has most of the  parallax functionality in there if you want to try recreating the effect.
